const core=$('Merge + Validate + Decide').item.json;
const rendered=$('Render Customer Reply').item.json;
const raw=String(rendered.text ?? rendered.output ?? rendered.response ?? '').trim();
const reply=raw.replace(/^```(?:text)?\s*/i,'').replace(/```$/,'').trim();
const verdictRaw=$json.output ?? $json;
const v=(verdictRaw && typeof verdictRaw==='object')?verdictRaw:{};
const semanticSafe=Boolean(v.safe) && v.language_match!==false && !v.claims_availability && !v.claims_booking_confirmed && !v.quotes_unverified_price && !v.assigns_vehicle && !v.attacks_competitor && !v.exposes_internal && v.asks_only_allowed_fields!==false && v.facts_match_plan!==false;
const reasons=[];
if(!reply)reasons.push('empty_reply');
if(reply.length>2500)reasons.push('reply_too_long');
if(/\b(?:HUMAN_REVIEW|NEEDS_INFO|NO_CHANGE|READY|extraction confidence|system prompt|internal status|automation workflow)\b/i.test(reply))reasons.push('internal_state_exposed');
if(/(?:[€$£]\s*\d)|(?:\b\d+(?:[.,]\d{1,2})?\s*(?:€|eur|euros?|usd|gbp|pounds?|dollars?)\b)/i.test(reply))reasons.push('unverified_numeric_price');
const confirms=[/\b(?:booking|reservation|availability)\b.{0,30}\b(?:confirmed|guaranteed|available)\b/i,/\b(?:buchung|reservierung|verfügbarkeit)\b.{0,30}\b(?:bestätigt|garantiert|verfügbar)\b/i,/\b(?:réservation|disponibilité)\b.{0,30}\b(?:confirmée?|garantie?|disponible)\b/i,/\b(?:prenotazione|disponibilità)\b.{0,30}\b(?:confermata|garantita|disponibile)\b/i,/\b(?:reserva|disponibilidad)\b.{0,30}\b(?:confirmada|garantizada|disponible)\b/i,/(?:κράτησ|διαθεσιμότ).{0,40}(?:επιβεβαι|διαθέσιμ|εγγυη)/i];
if(confirms.some(r=>r.test(reply)))reasons.push('booking_or_availability_claim');
if(/\b(?:your car is|we have assigned|vehicle assigned|car allocated)\b|(?:το όχημά σας είναι|σας έχει ανατεθεί όχημα)/i.test(reply))reasons.push('vehicle_assignment_claim');
if(/\b(?:scam|fraud|dishonest|cheat|fake price|rip[- ]?off)\b|(?:απάτη|απατεών|κοροϊδ)/i.test(reply))reasons.push('competitor_attack');
if(reply.includes('```'))reasons.push('markdown_code_fence');
if(!semanticSafe)reasons.push('semantic_verifier_rejected');
const safe=reasons.length===0;
const holding=core.reply_strategy==='SAFE_HOLDING_REPLY';
const logicAllows=Boolean(core.auto_send_allowed)||holding;
const send=Boolean(core.runtime?.auto_send_enabled)&&logicAllows&&safe&&core.reply_strategy!=='HOLD_FOR_HUMAN';
const reviewRequired=core.status==='HUMAN_REVIEW'||!safe;
const effectiveReason=[core.human_review_reason||'',...reasons].filter(Boolean).join(',');
const effectiveNext=!safe?'review_reply_before_send':core.next_action;
return [{json:{...core,reply_body:reply,reply_preview:reply.slice(0,400),reply_safe:safe,reply_safety_reasons:reasons,review_required:reviewRequired,effective_human_review_reason:effectiveReason,effective_next_action:effectiveNext,send_now:send,delivery_state:send?'PERSISTED_PENDING_SEND':(!safe?'HELD_REPLY_SAFETY':(core.runtime?.auto_send_enabled?'HELD':'DRAFT_ONLY'))}}];
