'use strict';
const REQUIRED_FIELDS=['customer_name','phone','pickup.date_text','return.date_text','vehicle.category'];
const HIGH_RISK=new Set(['return_before_pickup','conflicting_dates','conflicting_customer_identity','conflicting_phone','multiple_requests_in_one_message','conflicting_customer_name','conflicting_pickup_date_text','conflicting_return_date_text','conflicting_vehicle_category']);
const MEDIUM_INFO=new Set(['invalid_phone_format','ambiguous_numeric_date','ambiguous_pickup_numeric_date','ambiguous_return_numeric_date']);
const NEUTRAL={'vehicle.transmission':new Set(['unspecified','unknown','not specified'])};
const CORRECTABLE=new Set(['phone','email','pickup.date_text','pickup.date_iso','pickup.time_text','pickup.location','return.date_text','return.date_iso','return.time_text','return.location','vehicle.category','vehicle.category_normalized','vehicle.transmission','vehicle.model_text','competitor.price_text']);
const ALWAYS_MUTABLE=new Set(['language']);
const getPath=(o,p)=>p.split('.').reduce((v,k)=>v&&typeof v==='object'?v[k]:null,o);
const present=v=>!(v===null||v===undefined||(typeof v==='string'&&!v.trim()));
const neutral=(p,v)=>typeof v==='string'&&(NEUTRAL[p]||new Set()).has(v.trim().toLowerCase());
const equivalent=(p,a,b)=>typeof a==='string'&&typeof b==='string'?a.trim().toLowerCase()===b.trim().toLowerCase():a===b;
function setPath(o,p,v){const parts=p.split('.');let c=o;for(const x of parts.slice(0,-1)){if(!c[x]||typeof c[x]!=='object')c[x]={};c=c[x];}c[parts.at(-1)]=v;}
function missingRequired(x){const m=REQUIRED_FIELDS.filter(p=>!present(getPath(x,p)));if(present(x.phone)&&String(x.phone_status||'').startsWith('invalid')&&!m.includes('phone'))m.push('phone');return m;}
function safeIso(v){if(typeof v!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v))return null;const d=new Date(v+'T00:00:00Z');return Number.isNaN(d.getTime())?null:d;}
function contradictionReasons(x){const r=[];const p=safeIso(getPath(x,'pickup.date_iso')),q=safeIso(getPath(x,'return.date_iso'));if(p&&q&&q<p)r.push('return_before_pickup');if(x.multiple_requests)r.push('multiple_requests_in_one_message');for(const a of x.ambiguities||[]){if(!a||typeof a!=='object')continue;const code=String(a.code||''),sev=String(a.severity||'');if(sev==='high'||HIGH_RISK.has(code)){if(code&&!r.includes(code))r.push(code);}}return r;}
function decideStatus(x,{minimumConfidence=.85,duplicateMessage=false,inboundDisposition='PROCESS'}={}){if(inboundDisposition!=='PROCESS')return{status:'NO_CHANGE',missing_fields:[],human_review_reason:String(inboundDisposition).toLowerCase(),next_action:'ignore_non_customer_event',auto_send_allowed:false};if(duplicateMessage)return{status:'NO_CHANGE',missing_fields:[],human_review_reason:'duplicate_message_id',next_action:'ignore_duplicate_event',auto_send_allowed:false};const review=contradictionReasons(x);if(Number(x.confidence||0)<minimumConfidence)review.push('low_extraction_confidence');if(review.length)return{status:'HUMAN_REVIEW',missing_fields:missingRequired(x),human_review_reason:[...new Set(review)].join(','),next_action:'human_review_before_commitment',auto_send_allowed:false};let missing=missingRequired(x);for(const a of x.ambiguities||[]){if(!a||!MEDIUM_INFO.has(String(a.code||'')))continue;if(a.code==='invalid_phone_format'&&!missing.includes('phone'))missing.push('phone');if(a.code==='ambiguous_pickup_numeric_date'&&!missing.includes('pickup.date_text'))missing.push('pickup.date_text');if(a.code==='ambiguous_return_numeric_date'&&!missing.includes('return.date_text'))missing.push('return.date_text');if(a.code==='ambiguous_numeric_date'){for(const f of ['pickup.date_text','return.date_text'])if(!missing.includes(f))missing.push(f);}}if(missing.length)return{status:'NEEDS_INFO',missing_fields:missing,human_review_reason:'',next_action:'ask_only_missing_required_fields',auto_send_allowed:true};return{status:'READY',missing_fields:[],human_review_reason:'',next_action:'continue_to_availability_or_quote_step',auto_send_allowed:true};}
function ambiguityResolved(code,incoming){const codes=new Set((incoming.ambiguities||[]).filter(a=>a&&typeof a==='object').map(a=>String(a.code||'')));if(codes.has(code))return false;if(code==='invalid_phone_format')return present(incoming.phone)&&!String(incoming.phone_status||'').startsWith('invalid');if(code==='ambiguous_pickup_numeric_date')return present(getPath(incoming,'pickup.date_text'))||present(getPath(incoming,'pickup.date_iso'));if(code==='ambiguous_return_numeric_date')return present(getPath(incoming,'return.date_text'))||present(getPath(incoming,'return.date_iso'));if(code==='ambiguous_numeric_date')return present(getPath(incoming,'pickup.date_text'))&&present(getPath(incoming,'return.date_text'));return false;}
function dedupeAmbiguities(items){const out=[],seen=new Set();for(const a of items){if(!a||typeof a!=='object')continue;const k=String(a.code||'')+'\u0000'+String(a.detail||'');if(seen.has(k))continue;seen.add(k);out.push(a);}return out;}
function mergeExtractions(existing,incoming){const merged=structuredClone(existing),conflicts=[],corrections=[...(existing._applied_corrections||[])];const isCorrection=String(incoming.message_intent||'').toLowerCase()==='correction';const paths=['customer_name','phone','email','language','pickup.date_text','pickup.date_iso','pickup.time_text','pickup.location','return.date_text','return.date_iso','return.time_text','return.location','vehicle.category','vehicle.category_normalized','vehicle.transmission','vehicle.model_text','competitor.price_text'];for(const p of paths){const old=getPath(merged,p),nw=getPath(incoming,p);if(neutral(p,nw)||!present(nw))continue;if(ALWAYS_MUTABLE.has(p)){setPath(merged,p,nw);continue;}if(neutral(p,old)||!present(old)){setPath(merged,p,nw);continue;}if(equivalent(p,old,nw))continue;if(isCorrection&&CORRECTABLE.has(p)){setPath(merged,p,nw);corrections.push(p);}else conflicts.push(p);}merged._applied_corrections=[...new Set(corrections)];merged.message_intent=incoming.message_intent||existing.message_intent||'follow_up';merged.multiple_requests=Boolean(existing.multiple_requests)||Boolean(incoming.multiple_requests);merged.competitor=merged.competitor||{};merged.competitor.price_mentioned=Boolean(getPath(existing,'competitor.price_mentioned'))||Boolean(getPath(incoming,'competitor.price_mentioned'));const oc=Number(existing.confidence||0),nc=Number(incoming.confidence||0);merged.confidence=oc&&nc?Math.min(oc,nc):(nc||oc);if(present(incoming.phone)){merged.phone_raw=incoming.phone_raw;merged.phone_normalized=incoming.phone_normalized;merged.phone_status=incoming.phone_status;}else{merged.phone_raw=existing.phone_raw;merged.phone_normalized=existing.phone_normalized;merged.phone_status=existing.phone_status;}const carried=(existing.ambiguities||[]).filter(a=>a&&typeof a==='object'&&!ambiguityResolved(String(a.code||''),incoming)).map(a=>structuredClone(a));const newest=(incoming.ambiguities||[]).filter(a=>a&&typeof a==='object').map(a=>structuredClone(a));merged.ambiguities=[...carried,...newest];for(const p of conflicts)merged.ambiguities.push({code:`conflicting_${p.replaceAll('.','_')}`,severity:'high',detail:`Existing and follow-up values differ for ${p}`});merged.ambiguities=dedupeAmbiguities(merged.ambiguities);return[merged,conflicts];}
function buildReplyPlan(x,d,{holdingReplyEnabled=true}={}){let strategy='ACKNOWLEDGE_CONFIRM_VALUE_AND_NEXT_STEP';if(d.status==='NO_CHANGE')strategy='NO_REPLY';else if(d.status==='HUMAN_REVIEW')strategy=holdingReplyEnabled?'SAFE_HOLDING_REPLY':'HOLD_FOR_HUMAN';else if(d.status==='NEEDS_INFO')strategy='ACKNOWLEDGE_CONFIRM_ASK_ONLY_MISSING';return{language:x.language||'en',strategy,missing_fields:d.missing_fields||[],confirmed:{customer_name:x.customer_name,pickup_date:getPath(x,'pickup.date_text'),return_date:getPath(x,'return.date_text'),pickup_time:getPath(x,'pickup.time_text'),pickup_location:getPath(x,'pickup.location'),return_location:getPath(x,'return.location'),vehicle_category:getPath(x,'vehicle.category'),transmission:getPath(x,'vehicle.transmission')},include_total_cost_comparison:Boolean(getPath(x,'competitor.price_mentioned'))&&['READY','NEEDS_INFO'].includes(d.status),forbidden_claims:['availability_confirmed','booking_confirmed','exact_quote_without_source','vehicle_assignment'],must_not_attack_competitor:true};}
module.exports={decideStatus,mergeExtractions,buildReplyPlan,missingRequired,contradictionReasons,getPath};
